### ISSUE TITLE
Peer-to-peer review

### ISSUE THREAD

**Issue by yuvenalmash** [XRichardroidX/JEST-Testing-in-JS#3]
Good job so far on the project.

### There are some issues you need to look at
- Kindly move the tests to a 'tests' folder to make it easier to find them
- I suggest adding testing instructions in the README.md file

**Comment by XRichardroidX** [comment]
Thank you for your assistance in helping me make my project better, The issue has been fixed, Let me know if there is any feature issues, I'd really appreciate that, thank you.
